FROM node:14.15.5-alpine3.10



RUN apk add --update --no-cache bash \
#    && apk add --update --no-cache -t .build-deps python make g++ gcc git \
    && apk add --update --no-cache -t .build-deps python make g++ gcc git yarn curl py-pip \
    && apk del .build-deps


#RUN npm install
ENV PATH=node_modules/.bin:$PATH

WORKDIR /var/www/html
